config/routes.rb
Rails.application.routes.draw do
  
  # user
  devise_for :users
  
  # home
  root 'homes#top'
  get 'homes/about'
  
  # genre
  resources :genres, only: [:new, :create, :show, :edit, :update, :destroy]
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :get_genre
  protected

  def get_genre
    if user_signed_in?
      @genres = Genre.where(user_id: current_user.id)
    end
  end
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :set_genre, only:[:show, :edit, :update, :destroy]
  
  def new
    @genre = Genre.new
  end
  
  def create
    @genre = Genre.new(genre_params)
    @genre.user_id = current_user.id
    if @genre.save
      redirect_to @genre
    else
      render new
    end
  end
  
  def show
  end
  
  def edit
  end
  
  def update
    if @genre.update(genre_params)
      redirect_to @genre
    else
      render show
    end
  end
  
  def destroy
    @genre = Genre.destroy
    redirect_to root_path
  end
  
  private
  
  def set_genre
    @genre = Genre.find(params[:id])
  end
  
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/genres/edit.html.erb
<p>genre:edit</p>
<%= form_with model: @genre do |genre| %>
  <h3>ジャンル名</h3>
  <p>
    <%= genre.text_field :name %><br>
    <%= genre.submit "変更" %>
  </p>
<% end %>

app/views/genres/new.html.erb
<p>genre:new</p>
<%= form_with model: @genre do |genre| %>
  <h3>ジャンル名</h3>
  <p>
    <%= genre.text_field :name %><br>
    <%= genre.submit "作成" %>
  </p>
<% end %>

app/views/genres/show.html.erb
<p>genre:show</p>
<%= @genre.name %><br>
<%= @genre.user_id %>

app/views/homes/about.html.erb
<h1>Homes#about</h1>
<p>Find me in app/views/homes/about.html.erb</p>

app/views/homes/top.html.erb
<h1>Homes#top</h1>
<p>Find me in app/views/homes/top.html.erb</p>
<% if user_signed_in? %>
  <h2>メモ項目一覧</h2>
  <% if @genres.exists? %>
    <% @genres.each do |genre| %>
      <h3>
        <%= link_to genre.name, genre_path(genre.id) %>
        <%= link_to "編集", edit_genre_path(genre.id) %>
      </h3>
    <% end %><!--.each genre-->
  <% else %>
    <h3>メモがまだ存在しません</h3>
  <% end %>
<% else %><!--if user_signed_in?-->
  <h3>新規登録またはログインをすることでメモを作成できます</h3>
<% end %><!--if user_signed_in?-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PersonalMemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h2><%= link_to "トップへ", root_path %></h2>
      <% if user_signed_in? %>
        <p>
          ようこそ<br>
          <%= current_user.name %>
        </p>

        <p>
          <%= link_to "新規メモ", new_genre_path %>
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
        </p>

      <% else %><!--if user_signed_in?-->
        <p>
          <%= link_to "about",    homes_about_path %>
          <%= link_to "新規登録", new_user_registration_path %>
          <%= link_to "ログイン", new_user_session_path %>
        </p>
      <% end %><!--if user_signed_in?-->
    </header>
    
    <main>
      <%= yield %>
    </main>
    
    <footer>
      
    </footer>
  </body>
</html>